# This is a basic workflow to help you get started with Actions

name: sane-fmt

on: workflow_dispatch 
jobs:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - uses: sane-fmt/action@master
